export const userLoginTypes = {
  USER_LOGIN_BEGIN: "USER_LOGIN_BEGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL"
};

export const userRegisterTypes = {
  USER_REGISTER_BEGIN: "USER_REGISTER_BEGIN",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL"
};

export const userLogoutTypes = {
  USER_LOGOUT_BEGIN: "USER_LOGOUT_BEGIN",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAIL: "USER_LOGOUT_FAIL"
};
